#!/bin/bash
dotfiles_dir=`pwd -P`
home_dir=/etc/skel
echo "Installing dotfiles to ${home_dir}"
pushd $home_dir > /dev/null
ln -f -s $dotfiles_dir /tmp/dotfiles ;
chmod 0775 /tmp/dotfiles ;
sudo rsync -rlvtD --no-p --chmod=D0700,F600 /tmp/dotfiles/vim/ $home_dir
sudo rsync -rlvtD --no-p --chmod=D0700,F600 /tmp/dotfiles/zsh/ $home_dir
sudo rsync -rlvtD --no-p --chmod=D0700,F600 /tmp/dotfiles/ipython/ $home_dir
rm /tmp/dotfiles ;
sudo find ${home_dir} -mindepth 1 -type d -\! -name '.cache' -prune -\! -name 'pip' -prune -\! -name '.npm' -prune -exec sudo chmod 0700 {} \;
if [[ -d ${home_dir}/.ssh ]] ; then
  sudo find ${home_dir}/.ssh -type f -exec chmod 0600 {} \;
fi
popd > /dev/null

