#!/bin/bash
pushd `dirname $0` > /dev/null
dotfiles_dir=`pwd -P`
popd > /dev/null
user=${1:-`whoami`};
home_dir=$(eval echo "~${user}")
echo "Installing dotfiles for $user"
pushd $home_dir > /dev/null
sudo chsh -s `which zsh` $user;
ln -f -s $dotfiles_dir /tmp/dotfiles ;
chmod 0775 /tmp/dotfiles ;
sudo -u $user rsync -rltD /tmp/dotfiles/vim/ $home_dir
sudo -u $user rsync -rltD /tmp/dotfiles/zsh/ $home_dir
sudo -u $user rsync -rltD /tmp/dotfiles/ipython/ $home_dir
sudo -u $user rsync -rltD /tmp/dotfiles/screen/ $home_dir
rm /tmp/dotfiles ;
sudo find ${home_dir} -mindepth 1 -type d -exec sudo chmod 0700 {} \;

