#!/bin/bash
pushd $(dirname "$0") >/dev/null
dotfiles_dir=`pwd -P`
popd
rsync -rltD "${dotfiles_dir}/vim/" ~
rsync -rltD "${dotfiles_dir}/zsh/" ~
rsync -rltd "${dotfiles_dir}/ipython/" ~
rsync -rltd "${dotfiles_dir}/bash/" ~
if [[ -f zsh/$USER.zsh_aliases ]] ; then
  rm -f ~/.zsh_aliases
  cp ${dotifles_dir}/zsh/dbuy.zsh_aliases ~/.zsh_aliases
  cat ${dotfiles_dir}/zsh/$USER.zsh_aliases >>~/.zsh_aliases
else
  rm -f ~/.zsh_aliases
  cp ${dotfiles_dir}/zsh/dbuy.zsh_aliases ~/.zsh_aliases
fi
pushd ~
find . -mindepth 1 -type d -\! -name '.cache' -prune -\! -name 'pip' -prune -\! -name '.npm' -prune -exec chmod 0700 {} \;
popd
source ~/.zshrc || true

